### ISSUE TITLE
Bug: Tier 1 Raids Not Appearing on Map

### ISSUE THREAD

**Issue by RtheCuddleL** [PokeNavBot/MobileAppBeta#24] opened 2018-09-05 23:25 UTC
**Describe the bug**
Tier 1 Raid did not appear on the map, but appeared in the Nearby Tab.

**To Reproduce**
Added a Tier 1 Raid to #raid-screenshot-channel, 
PokeNav confirmed and created "Success Message".
Checked map for Tier 1 Raid and it was not there.  
Checked Nearby for Tier 1 raid and it appeared all the way at the bottom. 

**Expected behavior**
I would expect the Tier 1 raid to appear on the map as a pink egg with meta data attached when egg is selected.

**Screenshots**
Not available

**Smartphone (please complete the following information):**
Pixel 2
Android 9
iPhone 6s
iOS 11.4.1

**Comment by dandesousa** [comment] 2018-09-05 23:30
So tier 1 raids should appear on the map but currently requires an valid despawn / hatch time and a linked gym to appear

**Comment by dandesousa** [comment] 2018-09-05 23:31
This might have been due to the refresh interval. the map refreshes when you pan or zoom but not necessarily on an interval -- I should tie it to the same refresh interval as the nearby so they both auto update if you move. Do you recall if you left the map as is?

**Comment by RtheCuddleL** [comment] 2018-09-05 23:35
So I closed and reopened on both phones and neither one had it appear.  I was trying to test it at lunch again, but got tied up with work.

**Comment by dandesousa** [comment] 2018-09-06 14:00
Just did it with a tier 1 kabuto raid and was unable to reproduce. And actually confirmed existing logic will re-request all raids each time the map loads -- though the nearby might require manual refresh or a 3 minute refresh interval. 

Its possible that the nearby and map won't be exactly in sync, but the map will always be current. 


<img width="446" alt="screen shot 2018-09-06 at 9 56 17 am" src="https://user-images.githubusercontent.com/3880281/45162068-286c7f80-b1bb-11e8-96ae-975f87e6ed0b.png">

I am going to close this until we get confirmation that it exists -- confirmation would be

1. A screenshot of the raid report announcement in discord (so we can confirm that it has the gym and type) and a screenshot of it on the nearby but missing from the map.

**Closed as completed by dandesousa** 2018-09-06 14:00 UTC
Labels: bug
