### ISSUE TITLE
Dynamic Sort and Filtering on Nearby Raids Tab

### ISSUE THREAD

**Issue by RtheCuddleL** [PokeNavBot/MobileAppBeta#26] opened 2018-09-05 23:34 UTC
**Is your feature request related to a problem? Please describe.**
Allow users to sort Nearby Raids by Tier, Distance, and Time via Preferences or a mechanism to change sort on demand.

**Describe the solution you'd like**
Solution 1: Default preferences for sort order of Nearby Raids based on the 3 parameters above.
Solution 2: Filter/Sort button that opens a drop down menu that allows user to sort ascending or descending on parameters above.

**Describe alternatives you've considered**
Default sorting based on raid tier without mechanism for end-user to change.  

**Additional context**
The order of Nearby Raids for me on Android was Tier 4 > Tier 5> Tier 3> Tier 2> Tier 1  (Top>Bottom)
I would like a feature to adjust them based on meta data available.

**Comment by fortepc** [comment] 2018-09-06 03:45
Should be merged with #16

**Comment by alexisdesousa** [comment] 2018-09-06 19:20
Duplicate of #16

**Comment by dandesousa** [comment] 2018-10-05 19:16
Taking this over to #16 and closing

**Closed as completed by dandesousa** 2018-10-05 19:16 UTC
Labels: duplicate
