### ISSUE TITLE
Sort, Group, & Filter Features in the Nearby List

### ISSUE THREAD

**Issue by fortepc** [PokeNavBot/MobileAppBeta#16] opened 2018-09-05 17:09 UTC
**Describe the solution you'd like**
I'd like to see adjustable sort, group, and filter options in the nearby list. Being able to group by server, by raid level, by raid boss, by distance, etc

**Additional context**
Right now the nearby list doesn't appear to sort at all for me. It groups by raid tier, but the groups aren't sorted, my list had the order of Tier 2, then the Tier 4, then the tier 5, then the tier 3. Not sure if that's a bug or not.

**Comment by fortepc** [comment] 2018-09-05 17:11
Potential Group Options:

- Raid Tier 
- Raid Boss 
- Distance (0-1km, 1-10km, 10-25km, etc)
- Community (Group by which server has a raid party for that gym, if multiple servers have a raid party for that gym/raid, the one raid should appear in both groups)

**Comment by fortepc** [comment] 2018-09-05 17:12
Potential Sort Options: 

- Distance
- Attendees (people marked as coming in the discord parties)

**Comment by fortepc** [comment] 2018-09-05 17:14
Potential Filter Options: 

Raid Tier
Raid Boss
Distance (ie: adjustable range, within 25km, within 5km, within 100km)
Community (ability to filter to only raids that your server has a raid party for)

**Comment by alexisdesousa** [comment] 2018-09-06 19:18
Duplicate: #26

**Comment by alexisdesousa** [comment] 2018-09-06 19:19
Duplicate of #26

**Comment by alexisdesousa** [comment] 2018-09-06 19:21
Duplicate: #26

**Comment by dandesousa** [comment] 2018-10-05 19:16
additional comments

https://github.com/PokeNavBot/MobileAppBeta/issues/26#issue-357440915

**Comment by dandesousa** [comment] 2018-10-05 19:17
Communities out of scope for now, due to current display preferences but will consider in the future if there are many users with overlap

**Comment by dandesousa** [comment] 2018-10-06 14:12
scheduled for release in 1.1

**Closed as completed by dandesousa** 2018-10-06 14:12 UTC
Labels: enhancement
